spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://47.92.2.46:8084
  zipkin:
    base-url: http://47.92.2.46:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info