spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://47.92.2.46:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.92.2.46:8761/eureka/,http://47.92.2.46:8762/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info