spring:
  application:
    name: itoken-web-posts
  boot:
    admin:
      client:
        url: http://47.92.2.46:8084
  zipkin:
    base-url: http://47.92.2.46:9411
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8602
  #feign熔断器
feign:
  hystrix:
    enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.92.2.46:8761/eureka/,http://47.92.2.46:8762/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info