spring:
  boot:
    admin:
      client:
        url: http://47.92.2.46:8084
  zipkin:
    base-url: http://47.92.2.46:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.92.2.46:8761/eureka/,http://47.92.2.46:8762/eureka/
mybatis:
  type-aliases-package: com.coldcoder.iToken.common.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info